In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [13]:
df = pd.read_csv('../datasets/df_after_feature_selection.csv')
df.head()

                   location  total_sqft  bath   price  BHK  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1               Uttarahalli      1440.0   2.0   62.00    3     4305.555556
2        Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
3                  Kothanur      1200.0   2.0   51.00    2     4250.000000
4          Old Airport Road      2732.0   4.0  204.00    4     7467.057101

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8252 entries, 0 to 8251
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   location        8252 non-null   object
 1   total_sqft      8252 non-null   float64
 2   bath            8252 non-null   float64
 3   price           8252 non-null   float64
 4   BHK             8252 non-null   int64
 5   price_per_sqft  8252 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 386.9+ KB

In [16]:
df['location'].nunique()

240

**Areas with value count of greater than mean of the value counts are considered as main areas of bangalore.**

**Areas with value count of lesser or equal to the mean of the value counts are considered as other.**

In [17]:
df['location'].value_counts()

location
other                   1144
Whitefield               263
Sarjapur  Road           237
Thanisandra              147
Electronic City          142
                        ...
Sarakki Nagar              5
1st Block Jayanagar        3
2nd Stage Nagarbhavi       2
HAL 2nd Stage              2
Giri Nagar                 1
Name: count, Length: 240, dtype: int64

In [18]:
df_ohe_copy1 = df.copy()

In [19]:
df_ohe_copy1

                      location  total_sqft  bath   price  BHK  price_per_sqft
0     Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1                  Uttarahalli      1440.0   2.0   62.00    3     4305.555556
2           Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
3                     Kothanur      1200.0   2.0   51.00    2     4250.000000
4             Old Airport Road      2732.0   4.0  204.00    4     7467.057101
...                        ...         ...   ...     ...  ...             ...
8247               Uttarahalli      1345.0   2.0   57.00    3     4237.918216
8248         Green Glen Layout      1715.0   3.0  112.00    3     6530.612245
8249     Raja Rajeshwari Nagar      1141.0   2.0   60.00    2     5258.545136
8250           Padmanabhanagar      4689.0   4.0  488.00    4    10407.336319
8251              Doddathoguru       550.0   1.0   17.00    1     3090.909091

[8252 rows x 6 columns]

**Applying One Hot Encoding on Location Column.**

In [21]:
pd.get_dummies(df_ohe_copy1,columns=['location'])

,total_sqft,bath,price,BHK,price_per_sqft,location_ Devarachikkanahalli,location_1st Block Jayanagar,location_1st Phase JP Nagar,location_2nd Phase Judicial Layout,location_2nd Stage Nagarbhavi,...,location_Vishveshwarya Layout,location_Vishwapriya Layout,location_Vittasandra,location_Whitefield,location_Yelachenahalli,location_Yelahanka,location_Yelahanka New Town,location_Yelenahalli,location_Yeshwanthpur,location_other
0,1056.0,2.0,39.07,2,3699.810606,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1440.0,2.0,62.00,3,4305.555556,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1521.0,3.0,95.00,3,6245.890861,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1200.0,2.0,51.00,2,4250.000000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2732.0,4.0,204.00,4,7467.057101,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,1345.0,2.0,57.00,3,4237.918216,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8248,1715.0,3.0,112.00,3,6530.612245,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8249,1141.0,2.0,60.00,2,5258.545136,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8250,4689.0,4.0,488.00,4,10407.336319,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8251,550.0,1.0,17.00,1,3090.909091,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [22]:
pd.get_dummies(df_ohe_copy1.location,dtype='int')

,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8251,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
ohe = pd.get_dummies(df_ohe_copy1.location,dtype='int')
ohe

,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8251,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
ohe.drop(columns=['other'],inplace=True)

In [25]:
df_ohe_copy1.shape

(8252, 6)

In [27]:
concat_dummy = pd.concat([df_ohe_copy1, ohe], axis=1)

In [28]:
concat_dummy.location == 'other'

0       False
1       False
2       False
3       False
4       False
        ...
8247    False
8248    False
8249    False
8250    False
8251    False
Name: location, Length: 8252, dtype: bool

In [29]:
concat_dummy

,location,total_sqft,bath,price,BHK,price_per_sqft,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,Electronic City Phase II,1056.0,2.0,39.07,2,3699.810606,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Uttarahalli,1440.0,2.0,62.00,3,4305.555556,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Lingadheeranahalli,1521.0,3.0,95.00,3,6245.890861,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Kothanur,1200.0,2.0,51.00,2,4250.000000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Old Airport Road,2732.0,4.0,204.00,4,7467.057101,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,Uttarahalli,1345.0,2.0,57.00,3,4237.918216,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8248,Green Glen Layout,1715.0,3.0,112.00,3,6530.612245,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8249,Raja Rajeshwari Nagar,1141.0,2.0,60.00,2,5258.545136,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8250,Padmanabhanagar,4689.0,4.0,488.00,4,10407.336319,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8251,Doddathoguru,550.0,1.0,17.00,1,3090.909091,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
ohe = pd.get_dummies(df.location,dtype='int')
ohe

,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8248,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8249,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8250,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8251,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
ohe.drop(columns=['other'],inplace=True)

In [32]:
df = pd.concat([df, ohe], axis=1)

In [33]:
df.drop(columns=['location'],inplace=True)

In [34]:
df

,total_sqft,bath,price,BHK,price_per_sqft,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,1056.0,2.0,39.07,2,3699.810606,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1440.0,2.0,62.00,3,4305.555556,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1521.0,3.0,95.00,3,6245.890861,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1200.0,2.0,51.00,2,4250.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2732.0,4.0,204.00,4,7467.057101,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,1345.0,2.0,57.00,3,4237.918216,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8248,1715.0,3.0,112.00,3,6530.612245,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8249,1141.0,2.0,60.00,2,5258.545136,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8250,4689.0,4.0,488.00,4,10407.336319,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8251,550.0,1.0,17.00,1,3090.909091,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df.to_csv('../datasets/final_df.csv',index=False)

In [36]:
X = df.drop(columns=['price','price_per_sqft'])

In [37]:
y = df['price']

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [41]:
X_train

,total_sqft,bath,BHK,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
4580,1080.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1179,1345.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7356,990.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4391,1780.0,3.0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5675,1091.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4829,1245.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7291,1000.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1344,1160.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7293,1140.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1289,1546.0,3.0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train,y_train)
lr_clf.coef_

array([ 7.17980456e-02,  5.20748548e+00,  3.74861073e+00, -2.86122119e+01,
        7.09910294e+00,  1.87210623e+01, -3.27384245e+01, -5.19222582e+01,
       -5.42833315e+01, -2.29939320e+01,  6.07378445e+00, -4.53123166e+00,
       -2.96260924e+01, -2.51398720e+01, -2.12084166e+01, -3.39805622e+01,
       -2.02321042e+01, -7.29496784e+00, -8.45039521e-01, -4.89917517e+00,
       -2.39022833e+01, -2.98866127e+01, -2.67292805e+01, -2.51733280e+01,
       -1.99289748e+01, -1.36773088e+01, -2.48781628e+00,  5.74702905e+00,
       -5.55044736e+00, -1.90900958e+01, -2.74315049e+01, -1.07666430e+01,
        4.21351998e+00, -1.09122143e+01,  1.44144886e+01, -1.29930686e+01,
       -5.07425653e+01, -6.73716044e+01, -7.57140080e+00, -3.03595558e+01,
        1.96048077e+00, -1.35503048e+01,  3.95848493e+01,  1.07919858e-01,
       -2.28457870e+01, -4.34582004e+01, -3.31394345e+01, -1.18149191e+01,
        3.04847053e+01, -2.64250327e+01, -5.63369624e+00, -3.00829869e+00,
        1.56633085e+01, -2.44665971e+01, -2.30841265e+01, -3.01168769e+01,
       -3.95832864e+01,  1.35479558e+01, -5.04978014e+00, -1.61383854e+01,
       -1.15662130e+01,  1.04562218e+01, -2.42200030e+01, -4.21368387e+01,
       -6.76507753e+01, -1.99122015e+01, -2.40058500e+01, -1.95741994e+01,
        3.99565422e+01,  8.05894209e+00, -1.70044661e+01, -2.51325247e+01,
        8.13413790e+00, -2.36621695e+01, -3.90019220e+00, -3.88191172e+01,
       -2.71571946e+01,  1.36284883e+01, -3.81067671e+01, -1.13123671e+00,
       -1.51632495e+01, -3.13473522e+01, -1.32320675e+01,  4.58935399e+01,
       -3.00524197e+01, -1.60515993e+01, -3.01948581e+10, -3.31585975e+01,
       -2.80553404e+01, -1.28997298e+01, -2.18661907e+01, -3.41659854e+01,
        2.76441585e+01, -6.32132566e+00,  1.57029294e+00, -2.35992739e+01,
       -2.00220142e+01, -4.86595088e+00,  6.26744116e+00,  3.20977525e+01,
       -5.76805297e+00, -2.56220620e+01, -1.23850523e+01, -6.12596207e+00,
       -2.68976317e+01, -2.78221086e+01, -1.93529547e+01, -1.23429629e+01,
        1.16115166e+01, -2.68651701e+01, -2.76575217e+00, -1.04720455e+01,
       -2.54584619e+01, -4.29488171e+01,  2.21640442e+00,  2.91700444e+01,
       -7.31907018e+00,  3.82520628e-01, -5.57759640e-01, -1.31578401e+01,
       -9.41795369e+00, -1.48554591e+01, -2.82566365e+01, -7.35419287e+00,
       -1.37838495e+01, -2.87429125e+01, -8.32752845e+00, -1.75237217e+01,
       -1.78020315e+01, -3.95003528e+01, -1.69033936e+01, -1.63259304e+01,
       -2.96663351e+01, -2.45534955e+01, -1.65223951e+00, -1.44518003e+01,
       -2.58321603e+00, -9.67644223e+00, -1.17773142e+01, -1.51441203e+01,
       -1.77540881e+01, -1.21615993e+01, -1.07712757e+01, -2.09142547e+01,
       -3.27912860e+01, -2.66915184e+01, -1.90714892e+01,  2.49146424e+00,
        4.83143162e+01, -1.88320820e+01, -1.38887214e+01,  3.00766856e+01,
       -3.66339251e+01, -2.31494555e+01, -2.13367693e+01, -1.84305490e+01,
       -2.57045815e+01,  7.72830542e+00, -1.64700219e+01, -1.60970683e+01,
        2.31790036e+00, -1.09042187e+01, -7.07135222e+00, -1.91684791e+01,
       -9.10125428e-02, -1.93113444e+01, -2.57808233e+01,  2.73414581e+01,
       -1.03613651e+01, -1.72023010e+01, -2.85604103e+00, -4.04205681e+00,
       -2.42521355e+01, -1.70560847e+01, -8.64932143e+00, -1.98904710e+01,
       -3.01557541e+01, -1.54876797e+01, -5.93076700e+01, -1.86962113e+01,
        1.31330386e+01, -2.14912204e+01, -1.65690286e+01, -2.75060478e+01,
       -3.86111647e+00,  6.44884322e-01, -1.17443205e+01,  3.46956879e+00,
       -2.03822081e+01, -7.92605992e+00, -3.06360084e+01, -2.36392938e+01,
       -2.33905196e+01,  3.38884020e+00, -1.18832145e+01, -1.80011432e+01,
       -2.99042522e+01,  2.95432970e+01, -2.07400855e+01, -1.66776176e+01,
       -8.70779913e+00, -3.38909135e+01, -9.37385710e+00,  3.24172136e+00,
        3.61511230e+01, -2.05474901e+01, -1.56676714e+00, -4.32457007e+01,
        9.50990600e-01,  2.78972754e+01, -1.77035869e+01, -2.30367132e+01,
        5.48645616e+00, -1.98708906e+01, -1.17435293e+01, -3.38179940e+01,
       -1.59898672e+01, -1.31891097e+01, -2.30691589e+01, -1.42878323e+01,
       -1.53595196e+01, -1.30492085e+01,  5.36540005e+00, -1.04639440e+01,
       -1.94302347e+01, -1.98078641e+01,  2.58570376e+01, -2.92279521e+01,
       -2.08924456e+01, -2.47572958e+01, -3.11008297e+01, -1.95783640e+01,
       -1.83628441e+00, -7.89298982e+01, -3.61602872e+01, -2.16979421e+01,
       -4.74318544e+00, -8.83448362e+00, -1.71945803e+01, -2.70288799e+00,
       -3.43618879e+01,  7.75941906e+00])

In [42]:
lr_clf.score(X_test,y_test)

-131627652239409.6

In [40]:
from sklearn.metrics import r2_score
r2_score(y_test,lr_clf.predict(X_test))

-131627652239409.6